exports.water_turbines_data =
    [
        {
            id: "WP-1",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-2",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-3",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-4",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-5",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-6",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-7",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-8",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-9",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-10",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-11",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-12",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-13",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-14",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-15",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-16",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-17",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-17",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-18",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-19",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-20",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-21",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-22",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-23",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-24",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-25",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-26",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-27",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        },
        {
            id: "WP-28",
            symbol: '\u25C8',
            status: "on",
            description: "Installed since three month",
            rul: "900 ",
            risk: "10 %",
            nominal_impact: "3 %",
            expected_impact: "3 %",
            last_unscheduled_maintenance: "NA",
            average_subsystem_risk_level: "50 %",
            max_subsystem_risk_level: "70 %",
            average_exp_subsystem_impact: "50 %",
            high_exp_subsystem_impact: "70 %"
        }
    ];